apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolkit.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "coolkit.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 2345
      targetPort: observability
      protocol: TCP
      name: observability
  selector:
    {{- include "coolkit.selectorLabels" . | nindent 4 }}
